INSERT INTO voice_fragments (type, content, intensity, tags, line) VALUES

-- ZONA 01 — Comisuras
('comisuras_caidas','Se me caen las comisuras y tengo cara de estar enfadada todo el día.',5,ARRAY['comisuras','boca','cara triste','zona_01'],'RECOVER'),
('comisuras_caidas','Parezco triste aunque esté bien. Mi boca tira hacia abajo.',5,ARRAY['comisuras','tristeza','expresión','zona_01'],'RECOVER'),
('comisuras_caidas','Antes sonreía y se me marcaban los pómulos. Ahora todo cae.',4,ARRAY['comisuras','pómulos','caída','zona_01'],'RECOVER'),
('comisuras_caidas','Tengo cara de amargada y no lo soy.',5,ARRAY['comisuras','expresión','cara reposo','zona_01'],'RECOVER'),
('comisuras_caidas','Me dicen que estoy cansada y he dormido de maravilla.',4,ARRAY['comisuras','cansancio','expresión','zona_01'],'RECOVER'),
('comisuras_caidas','Las esquinas de mi boca han bajado y no sé cuándo pasó.',4,ARRAY['comisuras','boca','caída','zona_01'],'RECOVER'),
('comisuras_caidas','Siento que mi boca ya no sube igual cuando sonrío.',3,ARRAY['comisuras','sonrisa','tono','zona_01'],'RECOVER'),
('comisuras_caidas','Tengo como dos líneas que salen de las comisuras hacia abajo.',4,ARRAY['comisuras','líneas','marionetas','zona_01'],'RECOVER'),
('comisuras_caidas','Mi cara en reposo parece que está en modo serio permanente.',4,ARRAY['comisuras','cara reposo','expresión','zona_01'],'RECOVER'),
('comisuras_caidas','He visto fotos de hace tres años y mi boca era diferente, más levantada.',3,ARRAY['comisuras','fotos','comparación','zona_01'],'RECOVER'),
('comisuras_caidas','Me pregunta mi hija por qué pongo cara de pocos amigos.',5,ARRAY['comisuras','expresión','familia','zona_01'],'RECOVER'),
('comisuras_caidas','El contorno de mi boca ha perdido definición y se ve flácido.',4,ARRAY['comisuras','firmeza','contorno','zona_01'],'RECOVER'),
('comisuras_caidas','Tengo la sensación de que me pesa la cara en esa zona.',3,ARRAY['comisuras','peso','cara','zona_01'],'RECOVER'),
('comisuras_caidas','Las marionetas me están saliendo y soy joven.',5,ARRAY['comisuras','marionetas','joven','zona_01'],'RECOVER'),
('comisuras_caidas','Mi sonrisa ya no es simétrica, una comisura cae más que la otra.',4,ARRAY['comisuras','asimetría','sonrisa','zona_01'],'RECOVER'),

-- ZONA 02 — Frente
('rayas_frente','Tengo las rayas de la frente marcadísimas y cada vez se ven más.',4,ARRAY['frente','arrugas','rayas','zona_02'],'PREVENT'),
('rayas_frente','Me han salido tres líneas horizontales en la frente y no puedo quitármelas de la cabeza.',4,ARRAY['frente','líneas horizontales','preocupación','zona_02'],'PREVENT'),
('rayas_frente','Cuando no me maquillo se me ven unas arrugas en la frente que me hacen parecer mayor.',4,ARRAY['frente','maquillaje','arrugas','zona_02'],'PREVENT'),
('rayas_frente','Frunzo el ceño sin darme cuenta y ya tengo esas líneas grabadas.',4,ARRAY['frente','ceño','inconsciente','zona_02'],'PREVENT'),
('rayas_frente','Mi frente parece un papel arrugado cuando levanto las cejas.',3,ARRAY['frente','cejas','textura','zona_02'],'PREVENT'),
('rayas_frente','Me he dado cuenta de que tengo la frente con textura, no está lisa como antes.',3,ARRAY['frente','textura','cambio','zona_02'],'PREVENT'),
('rayas_frente','Las líneas de la frente se me notan incluso con base de maquillaje.',4,ARRAY['frente','maquillaje','base','zona_02'],'PREVENT'),
('rayas_frente','Me preocupa que a mi edad ya tenga estas arrugas tan marcadas en la frente.',4,ARRAY['frente','edad','preocupación','zona_02'],'PREVENT'),
('rayas_frente','Parece que estoy siempre preocupada o concentrada aunque esté tranquila.',4,ARRAY['frente','expresión','estrés','zona_02'],'PREVENT'),
('rayas_frente','Tengo la frente muy brillante y con poros grandes, no sé cómo equilibrarla.',3,ARRAY['frente','brillante','poros','zona_02'],'PREVENT'),
('rayas_frente','Duermo bien pero me levanto con la frente tensa y con marcas.',3,ARRAY['frente','tensión','mañana','zona_02'],'PREVENT'),
('rayas_frente','He empezado a notar que las arrugas de la frente no desaparecen aunque relaje la cara.',4,ARRAY['frente','arrugas estáticas','relajar','zona_02'],'PREVENT'),
('rayas_frente','El estrés del trabajo se me ha instalado en la frente, literalmente.',5,ARRAY['frente','estrés','trabajo','zona_02'],'PREVENT'),
('rayas_frente','Mi frente está apagada y sin vida, no tiene ese brillo que tenía antes.',3,ARRAY['frente','apagada','luminosidad','zona_02'],'PREVENT'),
('rayas_frente','Me han dicho que debería ponerme bótox en la frente y no quiero llegar a eso.',5,ARRAY['frente','bótox','prevención','zona_02'],'PREVENT'),

-- ZONA 03 — Ojeras
('ojeras_bolsas','Tengo unas ojeras permanentes que no se me quitan ni durmiendo bien.',5,ARRAY['ojeras','permanentes','dormir','zona_03'],'RECOVER'),
('ojeras_bolsas','Me preguntan constantemente si estoy cansada y he dormido ocho horas.',5,ARRAY['ojeras','cansancio','preguntas','zona_03'],'RECOVER'),
('ojeras_bolsas','Las bolsas de los ojos me hacen parecer mayor de lo que soy.',4,ARRAY['bolsas','ojos','edad','zona_03'],'RECOVER'),
('ojeras_bolsas','Me levanto por las mañanas con los ojos hinchados y no sé por qué.',4,ARRAY['bolsas','hinchazón','mañana','zona_03'],'RECOVER'),
('ojeras_bolsas','Tengo unas manchas oscuras bajo los ojos que no cubre ni el corrector.',5,ARRAY['ojeras','corrector','manchas','zona_03'],'RECOVER'),
('ojeras_bolsas','Mis ojos parecen hundidos y con sombra aunque esté descansada.',4,ARRAY['ojeras','hundidos','sombra','zona_03'],'RECOVER'),
('ojeras_bolsas','La zona bajo mis ojos siempre se ve apagada y sin vida.',4,ARRAY['ojeras','apagada','bajo ojo','zona_03'],'RECOVER'),
('ojeras_bolsas','Tengo como una bolsita debajo del ojo que ha aparecido de la nada.',4,ARRAY['bolsas','aparición','repentina','zona_03'],'RECOVER'),
('ojeras_bolsas','El corrector se me mete en las arruguitas bajo el ojo y se ve peor.',3,ARRAY['ojeras','corrector','maquillaje','zona_03'],'RECOVER'),
('ojeras_bolsas','Noto que la piel bajo mis ojos es muy fina y se ve la vena.',3,ARRAY['ojeras','piel fina','venas','zona_03'],'RECOVER'),
('ojeras_bolsas','He probado mil cremas de contorno de ojos y ninguna funciona de verdad.',5,ARRAY['ojeras','cremas','frustración','zona_03'],'RECOVER'),
('ojeras_bolsas','Me han salido unas líneas finitas bajo el ojo que antes no tenía.',3,ARRAY['ojeras','líneas finas','cambio','zona_03'],'RECOVER'),
('ojeras_bolsas','Parece que tengo siempre cara de no haber dormido, aunque esté perfectamente.',5,ARRAY['ojeras','cansancio','expresión','zona_03'],'RECOVER'),
('ojeras_bolsas','La hinchazón de los ojos por la mañana me dura hasta el mediodía.',4,ARRAY['bolsas','hinchazón','drenaje','zona_03'],'RECOVER'),
('ojeras_bolsas','Desde que trabajo más horas con el ordenador tengo las ojeras mucho peor.',4,ARRAY['ojeras','pantallas','trabajo','zona_03'],'RECOVER'),

-- ZONA 04 — Mejillas
('pomulos_perdidos','He perdido los pómulos. Antes los tenía marcados y ahora no se ven.',5,ARRAY['pómulos','pérdida','mejillas','zona_04'],'RECLAIM'),
('pomulos_perdidos','Mis mejillas han caído y tengo la cara más plana que antes.',4,ARRAY['mejillas','caída','cara plana','zona_04'],'RECLAIM'),
('pomulos_perdidos','Siento que se me ha ido el volumen de la cara y me veo mayor.',4,ARRAY['mejillas','volumen','mayor','zona_04'],'RECLAIM'),
('pomulos_perdidos','Antes tenía cara de corazón y ahora la tengo cuadrada.',4,ARRAY['mejillas','forma cara','corazón','zona_04'],'RECLAIM'),
('pomulos_perdidos','Mis mejillas ya no tienen esa jugosidad que tenían, están como vacías.',4,ARRAY['mejillas','jugosidad','vacías','zona_04'],'RECLAIM'),
('pomulos_perdidos','La parte de abajo de mi cara pesa más que la de arriba.',3,ARRAY['mejillas','peso','caída','zona_04'],'RECLAIM'),
('pomulos_perdidos','He perdido la definición de los pómulos y ya no sé cómo contornearme.',3,ARRAY['pómulos','maquillaje','definición','zona_04'],'RECLAIM'),
('pomulos_perdidos','Me han dicho que me ponga relleno en los pómulos y no quiero llegar a eso.',5,ARRAY['pómulos','filler','prevención','zona_04'],'RECLAIM'),
('pomulos_perdidos','Mi cara se ve cansada porque las mejillas han bajado.',4,ARRAY['mejillas','cansancio','bajado','zona_04'],'RECLAIM'),
('pomulos_perdidos','Cuando me río ya no se me marcan los pómulos como antes.',3,ARRAY['pómulos','sonrisa','cambio','zona_04'],'RECLAIM'),
('pomulos_perdidos','Noto que el maquillaje se cae hacia abajo porque mi piel ya no lo sostiene.',3,ARRAY['mejillas','maquillaje','firmeza','zona_04'],'RECLAIM'),
('pomulos_perdidos','Las fotos de perfil me matan porque se me ve la mejilla caída.',4,ARRAY['mejillas','fotos','perfil','zona_04'],'RECLAIM'),
('pomulos_perdidos','Tengo la sensación de que mi cara ha perdido su forma, ya no es la misma.',5,ARRAY['mejillas','identidad','forma','zona_04'],'RECLAIM'),
('pomulos_perdidos','He adelgazado y se me han hundido las mejillas, estoy desencajada.',4,ARRAY['mejillas','adelgazar','hundidas','zona_04'],'RECLAIM'),
('pomulos_perdidos','La gente me dice que me veo diferente pero no saben exactamente qué ha cambiado.',4,ARRAY['mejillas','cambio','identidad','zona_04'],'RECLAIM'),

-- ZONA 05 — Surco Nasogeniano
('pliegues_sonrisa','Se me están marcando los surcos de la sonrisa y cada vez más profundos.',5,ARRAY['nasogeniano','surcos','sonrisa','zona_05'],'RECOVER'),
('pliegues_sonrisa','Tengo esas líneas que van de la nariz a la boca y me hacen parecer mayor.',5,ARRAY['nasogeniano','nariz','boca','zona_05'],'RECOVER'),
('pliegues_sonrisa','Los pliegues de la cara me han salido de repente y no sé cómo quitármelos.',5,ARRAY['nasogeniano','pliegues','repentino','zona_05'],'RECOVER'),
('pliegues_sonrisa','Me miro al espejo y lo primero que veo son esos surcos tan marcados.',5,ARRAY['nasogeniano','espejo','preocupación','zona_05'],'RECOVER'),
('pliegues_sonrisa','Tengo cara de bulldog, con esos pliegues cayendo a los lados de la boca.',4,ARRAY['nasogeniano','bulldog','caída','zona_05'],'RECOVER'),
('pliegues_sonrisa','He bajado de peso y se me han marcado mucho los surcos nasogenianos.',4,ARRAY['nasogeniano','adelgazar','marcado','zona_05'],'RECOVER'),
('pliegues_sonrisa','Las líneas de la sonrisa ya no desaparecen cuando dejo de sonreír.',5,ARRAY['nasogeniano','líneas estáticas','sonrisa','zona_05'],'RECOVER'),
('pliegues_sonrisa','Con luz lateral se me ven unos surcos en la cara que me afectan mucho.',4,ARRAY['nasogeniano','luz lateral','surcos','zona_05'],'RECOVER'),
('pliegues_sonrisa','He probado cremas antiarrugas para los surcos y no me funcionan.',5,ARRAY['nasogeniano','cremas','frustración','zona_05'],'RECOVER'),
('pliegues_sonrisa','El maquillaje se me mete en esos pliegues y se ve peor que sin nada.',4,ARRAY['nasogeniano','maquillaje','pliegues','zona_05'],'RECOVER'),
('pliegues_sonrisa','Siento que mi cara ha perdido firmeza justo en esa zona central.',4,ARRAY['nasogeniano','firmeza','tercio medio','zona_05'],'RECOVER'),
('pliegues_sonrisa','Me han dicho que me ponga ácido hialurónico en los surcos pero me da miedo.',5,ARRAY['nasogeniano','filler','miedo','zona_05'],'RECOVER'),
('pliegues_sonrisa','Los pliegues de la cara me hacen sentir que he envejecido de golpe.',5,ARRAY['nasogeniano','envejecimiento','golpe','zona_05'],'RECOVER'),
('pliegues_sonrisa','Noto que la zona entre la nariz y la boca tiene la piel más fina y caída.',3,ARRAY['nasogeniano','piel fina','caída','zona_05'],'RECOVER'),
('pliegues_sonrisa','Mi madre tiene los mismos surcos y me da pánico acabar igual de marcada.',4,ARRAY['nasogeniano','genética','miedo','zona_05'],'RECOVER'),

-- ZONA 06 — Entrecejo
('lineas_entrecejo','Tengo las líneas del entrecejo muy marcadas y parezco siempre enfadada.',5,ARRAY['entrecejo','signo 11','enfadada','zona_06'],'PREVENT'),
('lineas_entrecejo','Se me han quedado grabadas las rayas del ceño y no desaparecen aunque esté relajada.',5,ARRAY['entrecejo','rayas','estáticas','zona_06'],'PREVENT'),
('lineas_entrecejo','Frunzo el ceño sin darme cuenta y ya noto que se me está quedando la arruga.',4,ARRAY['entrecejo','inconsciente','arruga','zona_06'],'PREVENT'),
('lineas_entrecejo','Tengo el signo del 11 entre las cejas y me hace parecer seria todo el tiempo.',5,ARRAY['entrecejo','signo 11','seria','zona_06'],'PREVENT'),
('lineas_entrecejo','Mi entrecejo dice que estoy preocupada aunque esté tranquila.',4,ARRAY['entrecejo','preocupación','expresión','zona_06'],'PREVENT'),
('lineas_entrecejo','Me han dicho que el bótox en el entrecejo es lo primero que debería hacer.',5,ARRAY['entrecejo','bótox','consejo','zona_06'],'PREVENT'),
('lineas_entrecejo','Trabajo mucho con pantallas y noto que el ceño se me frunce sin querer.',4,ARRAY['entrecejo','pantallas','trabajo','zona_06'],'PREVENT'),
('lineas_entrecejo','Tengo una arruga horizontal en el puente de la nariz que me preocupa.',3,ARRAY['entrecejo','nariz','horizontal','zona_06'],'PREVENT'),
('lineas_entrecejo','Cuando me miro fotos veo siempre el entrecejo tenso, nunca relajado.',4,ARRAY['entrecejo','fotos','tensión','zona_06'],'PREVENT'),
('lineas_entrecejo','El estrés se me ha instalado literalmente entre las cejas.',5,ARRAY['entrecejo','estrés','tensión','zona_06'],'PREVENT'),
('lineas_entrecejo','Mis hijos me dicen que parezco enfadada cuando estoy concentrada.',4,ARRAY['entrecejo','familia','expresión','zona_06'],'PREVENT'),
('lineas_entrecejo','He empezado a notar que el ceño fruncido me está dejando marca permanente.',4,ARRAY['entrecejo','marca permanente','preocupación','zona_06'],'PREVENT'),
('lineas_entrecejo','Duermo con el ceño fruncido y me levanto con las líneas marcadas por las mañanas.',3,ARRAY['entrecejo','dormir','mañana','zona_06'],'PREVENT'),
('lineas_entrecejo','Tengo miedo de que las líneas del entrecejo se hagan cada vez más profundas.',4,ARRAY['entrecejo','miedo','profundas','zona_06'],'PREVENT'),
('lineas_entrecejo','No quiero ponerme bótox en el entrecejo pero tampoco quiero seguir viendo esas líneas.',5,ARRAY['entrecejo','bótox','alternativa','zona_06'],'PREVENT'),

-- ZONA 07 — Cuello y Óvalo
('papada_ovalo_caido','Se me ha caído el óvalo de la cara y ya no tengo la mandíbula definida.',5,ARRAY['cuello','óvalo','mandíbula','zona_07'],'RECLAIM'),
('papada_ovalo_caido','Tengo papada y no entiendo por qué si no he engordado.',5,ARRAY['cuello','papada','peso','zona_07'],'RECLAIM'),
('papada_ovalo_caido','El cuello se me ha llenado de arrugas y no sé qué hacer.',4,ARRAY['cuello','arrugas','cervical','zona_07'],'RECLAIM'),
('papada_ovalo_caido','He perdido la definición de la mandíbula y tengo la cara cuadrada por abajo.',4,ARRAY['cuello','mandíbula','cuadrada','zona_07'],'RECLAIM'),
('papada_ovalo_caido','Se me están marcando las bandas del cuello y me hacen parecer muy mayor.',5,ARRAY['cuello','bandas','platisma','zona_07'],'RECLAIM'),
('papada_ovalo_caido','Tengo el cuello más viejo que mi cara y se nota el contraste.',5,ARRAY['cuello','contraste','cara','zona_07'],'RECLAIM'),
('papada_ovalo_caido','Desde que miro tanto el móvil tengo el cuello horrible.',4,ARRAY['cuello','móvil','text neck','zona_07'],'RECLAIM'),
('papada_ovalo_caido','Me han salido unas arrugas horizontales en el cuello que no me gustan nada.',4,ARRAY['cuello','arrugas horizontales','cervical','zona_07'],'RECLAIM'),
('papada_ovalo_caido','Cuido mucho mi cara pero el cuello lo tengo olvidado y se nota.',4,ARRAY['cuello','olvidado','rutina','zona_07'],'RECLAIM'),
('papada_ovalo_caido','La papada aparece siempre en las fotos aunque esté en mi peso.',5,ARRAY['cuello','papada','fotos','zona_07'],'RECLAIM'),
('papada_ovalo_caido','He bajado de peso y la piel del cuello me ha quedado flácida y sin tono.',4,ARRAY['cuello','flácida','adelgazar','zona_07'],'RECLAIM'),
('papada_ovalo_caido','El óvalo de mi cara ya no es el de antes, se ha desdibujado hacia abajo.',5,ARRAY['cuello','óvalo','abajo','zona_07'],'RECLAIM'),
('papada_ovalo_caido','Tengo la sensación de que el cuello me ha envejecido de golpe este año.',4,ARRAY['cuello','envejecimiento','repentino','zona_07'],'RECLAIM'),
('papada_ovalo_caido','Me pongo crema en la cara pero nunca en el cuello y ya lo estoy pagando.',4,ARRAY['cuello','rutina','olvido','zona_07'],'RECLAIM'),
('papada_ovalo_caido','La mandíbula ya no se me ve marcada, todo se ha fundido hacia abajo.',4,ARRAY['cuello','mandíbula','fundido','zona_07'],'RECLAIM'),

-- ZONA 08 — Labios
('codigo_barras_labios','Se me están marcando las arruguitas encima del labio y me hacen mayor.',4,ARRAY['labios','código barras','arrugas','zona_08'],'RECLAIM'),
('codigo_barras_labios','Tengo el código de barras encima de la boca y no sé cómo quitármelo.',5,ARRAY['labios','código barras','contorno','zona_08'],'RECLAIM'),
('codigo_barras_labios','Mis labios se han afinado con los años y ya no tengo el volumen de antes.',4,ARRAY['labios','finos','volumen','zona_08'],'RECLAIM'),
('codigo_barras_labios','El labio superior se me ha caído y ya no se me ve casi al sonreír.',4,ARRAY['labios','superior','caído','zona_08'],'RECLAIM'),
('codigo_barras_labios','El pintalabios se me mete en las arrugas del contorno y queda horrible.',4,ARRAY['labios','pintalabios','maquillaje','zona_08'],'RECLAIM'),
('codigo_barras_labios','He perdido la definición del contorno del labio, el borde ya no se ve.',4,ARRAY['labios','borde','contorno','zona_08'],'RECLAIM'),
('codigo_barras_labios','El surco entre la nariz y el labio se ha aplanado y me cambia la cara.',3,ARRAY['labios','filtrum','nariz','zona_08'],'RECLAIM'),
('codigo_barras_labios','Noto que los labios los tengo más finos y arrugados que antes.',4,ARRAY['labios','finos','arrugados','zona_08'],'RECLAIM'),
('codigo_barras_labios','Me han dicho que me ponga relleno en los labios pero no quiero ese efecto.',5,ARRAY['labios','filler','natural','zona_08'],'RECLAIM'),
('codigo_barras_labios','El contorno de mi boca tiene unas líneas finísimas que se marcan con el maquillaje.',3,ARRAY['labios','líneas finas','maquillaje','zona_08'],'RECLAIM'),
('codigo_barras_labios','Siento que mi boca ha perdido presencia y expresión con los años.',4,ARRAY['labios','presencia','expresión','zona_08'],'RECLAIM'),
('codigo_barras_labios','Tengo las líneas de expresión alrededor de la boca muy marcadas.',4,ARRAY['labios','expresión','contorno','zona_08'],'RECLAIM'),
('codigo_barras_labios','He fumado mucho y noto que el contorno del labio está muy arrugado.',4,ARRAY['labios','tabaco','contorno','zona_08'],'RECLAIM'),
('codigo_barras_labios','Mi labio inferior parece que ha bajado y ya no está donde estaba.',3,ARRAY['labios','inferior','caído','zona_08'],'RECLAIM'),
('codigo_barras_labios','La zona alrededor de mi boca ha perdido firmeza y se ve flácida.',4,ARRAY['labios','firmeza','flácida','zona_08'],'RECLAIM'),

-- ZONA 09 — Mandíbula
('mandibula_tensa','Tengo la mandíbula muy marcada y me da cara cuadrada.',4,ARRAY['mandíbula','cuadrada','masetero','zona_09'],'RECOVER'),
('mandibula_tensa','Me aprieto los dientes sin darme cuenta y tengo la mandíbula siempre tensa.',5,ARRAY['mandíbula','bruxismo','inconsciente','zona_09'],'RECOVER'),
('mandibula_tensa','Tengo bruxismo y se me ve la mandíbula muy desarrollada.',4,ARRAY['mandíbula','bruxismo','hipertrofia','zona_09'],'RECOVER'),
('mandibula_tensa','Me duele la mandíbula por las mañanas de tanto apretar por la noche.',5,ARRAY['mandíbula','dolor','noche','zona_09'],'RECOVER'),
('mandibula_tensa','El estrés se me va directo a la mandíbula y a las sienes.',5,ARRAY['mandíbula','estrés','sienes','zona_09'],'RECOVER'),
('mandibula_tensa','Noto que tengo la cara más cuadrada que antes y creo que es por el estrés.',4,ARRAY['mandíbula','cuadrada','estrés','zona_09'],'RECOVER'),
('mandibula_tensa','Me han dicho que me ponga bótox en el masetero para adelgazar la mandíbula.',5,ARRAY['mandíbula','bótox','masetero','zona_09'],'RECOVER'),
('mandibula_tensa','Tengo la zona de la mandíbula muy tensa y me genera dolor de cabeza.',5,ARRAY['mandíbula','tensión','cefalea','zona_09'],'RECOVER'),
('mandibula_tensa','La piel de la zona de la mandíbula la noto más apagada que el resto.',3,ARRAY['mandíbula','apagada','piel','zona_09'],'RECOVER'),
('mandibula_tensa','Me han salido unas líneas en la zona de la mandíbula que no entiendo por qué.',3,ARRAY['mandíbula','líneas','confusión','zona_09'],'RECOVER'),
('mandibula_tensa','Duermo con la mandíbula apretada y me levanto con la cara tensa y rígida.',5,ARRAY['mandíbula','dormir','rigidez','zona_09'],'RECOVER'),
('mandibula_tensa','El contorno de mi mandíbula ha perdido definición y se confunde con el cuello.',4,ARRAY['mandíbula','contorno','cuello','zona_09'],'RECOVER'),
('mandibula_tensa','Tengo la sensación de que cargo todo el peso del estrés en la mandíbula.',5,ARRAY['mandíbula','estrés','carga','zona_09'],'RECOVER'),
('mandibula_tensa','He empezado a usar férula dental de noche por el bruxismo y mi mandíbula está enorme.',4,ARRAY['mandíbula','férula','bruxismo','zona_09'],'RECOVER'),
('mandibula_tensa','La tensión de la mandíbula me sube a las sienes y me baja al cuello.',4,ARRAY['mandíbula','sienes','cuello','zona_09'],'RECOVER'),

-- ZONA 10 — Párpado Superior
('parpado_caido','Se me ha caído el párpado y me achica el ojo.',5,ARRAY['párpado','caído','ojo','zona_10'],'RECOVER'),
('parpado_caido','Tengo los ojos cada vez más pequeños porque el párpado me tapa la mirada.',5,ARRAY['párpado','ojos pequeños','mirada','zona_10'],'RECOVER'),
('parpado_caido','Me dicen que parezco somnoliente aunque esté completamente despierta.',4,ARRAY['párpado','somnoliente','expresión','zona_10'],'RECOVER'),
('parpado_caido','El párpado superior se me ha caído y ya no me llega hasta el borde del ojo.',4,ARRAY['párpado','borde','caído','zona_10'],'RECOVER'),
('parpado_caido','He perdido el pliegue del párpado y ya no se me ve igual cuando me maquillo.',4,ARRAY['párpado','pliegue','maquillaje','zona_10'],'RECOVER'),
('parpado_caido','Me cuesta ponerme sombra de ojos porque el párpado ha caído.',3,ARRAY['párpado','sombra','maquillaje','zona_10'],'RECOVER'),
('parpado_caido','Tengo los ojos más pequeños que hace unos años y me afecta mucho.',4,ARRAY['párpado','ojos','comparación','zona_10'],'RECOVER'),
('parpado_caido','La piel del párpado la noto muy fina y arrugada cuando me la toco.',3,ARRAY['párpado','piel fina','arrugada','zona_10'],'RECOVER'),
('parpado_caido','Me he dado cuenta de que el párpado derecho me cae más que el izquierdo.',3,ARRAY['párpado','asimetría','derecho','zona_10'],'RECOVER'),
('parpado_caido','Parece que estoy siempre a punto de dormirme por culpa del párpado.',4,ARRAY['párpado','somnoliento','expresión','zona_10'],'RECOVER'),
('parpado_caido','He estado pensando en operarme los párpados porque me tapan la mirada.',5,ARRAY['párpado','cirugía','blefaroplastia','zona_10'],'RECOVER'),
('parpado_caido','Las arruguitas del párpado superior se me marcan mucho con el maquillaje.',3,ARRAY['párpado','arrugas','maquillaje','zona_10'],'RECOVER'),
('parpado_caido','Antes tenía una mirada más intensa y ahora parece que está apagada.',4,ARRAY['párpado','mirada','intensidad','zona_10'],'RECOVER'),
('parpado_caido','El surco del párpado se me ha hundido y me da un aspecto de cansancio.',4,ARRAY['párpado','surco','hundido','zona_10'],'RECOVER'),
('parpado_caido','Mi mirada ha perdido presencia y ya no expresa lo que quiero expresar.',5,ARRAY['párpado','mirada','presencia','zona_10'],'RECOVER'),

-- ZONA 11 — Pómulo Malar
('pomulos_hundidos','He perdido los pómulos y no sé cuándo pasó exactamente.',4,ARRAY['pómulo','malar','pérdida','zona_11'],'RECLAIM'),
('pomulos_hundidos','Antes tenía los pómulos muy marcados y ahora no se ven nada.',5,ARRAY['pómulo','marcados','cambio','zona_11'],'RECLAIM'),
('pomulos_hundidos','Mi cara ha perdido estructura y parece que todo ha bajado.',5,ARRAY['pómulo','estructura','bajado','zona_11'],'RECLAIM'),
('pomulos_hundidos','Los pómulos se me han hundido y me cambia completamente la cara.',5,ARRAY['pómulo','hundidos','cara','zona_11'],'RECLAIM'),
('pomulos_hundidos','Desde que adelgacé se me fueron los pómulos y no han vuelto.',4,ARRAY['pómulo','adelgazar','perdido','zona_11'],'RECLAIM'),
('pomulos_hundidos','Noto que un pómulo me ha bajado más que el otro y se ve asimétrico.',3,ARRAY['pómulo','asimetría','bajado','zona_11'],'RECLAIM'),
('pomulos_hundidos','Me han dicho que me ponga relleno en los pómulos para recuperar el volumen.',5,ARRAY['pómulo','filler','volumen','zona_11'],'RECLAIM'),
('pomulos_hundidos','La zona del pómulo la tengo hundida y me crea una sombra fea en la cara.',4,ARRAY['pómulo','hundida','sombra','zona_11'],'RECLAIM'),
('pomulos_hundidos','He perdido la proyección del pómulo y la cara me ha quedado plana.',4,ARRAY['pómulo','proyección','plana','zona_11'],'RECLAIM'),
('pomulos_hundidos','Cuando me contorneo intento recuperar los pómulos que ya no tengo.',3,ARRAY['pómulo','maquillaje','contorno','zona_11'],'RECLAIM'),
('pomulos_hundidos','El pómulo era lo que más me gustaba de mi cara y ya no lo tengo.',5,ARRAY['pómulo','identidad','pérdida','zona_11'],'RECLAIM'),
('pomulos_hundidos','Siento que mi cara ha bajado entera y el pómulo ha desaparecido.',5,ARRAY['pómulo','bajado','desaparecido','zona_11'],'RECLAIM'),
('pomulos_hundidos','Desde la menopausia noto que he perdido volumen en toda la zona de los pómulos.',5,ARRAY['pómulo','menopausia','volumen','zona_11'],'RECLAIM'),
('pomulos_hundidos','Las fotos de hace cinco años y las de ahora son completamente diferentes en los pómulos.',4,ARRAY['pómulo','fotos','comparación','zona_11'],'RECLAIM'),
('pomulos_hundidos','Sin los pómulos marcados, la cara me parece sin vida y sin carácter.',5,ARRAY['pómulo','carácter','identidad','zona_11'],'RECLAIM'),

-- ZONA 12 — Nariz y Poros
('poros_puntos_negros','Tengo los poros de la nariz enormes y no hay forma de reducirlos.',5,ARRAY['poros','nariz','grandes','zona_12'],'PREVENT'),
('poros_puntos_negros','Los puntos negros de la nariz me vuelven loca, siempre están ahí.',5,ARRAY['poros','puntos negros','obsesión','zona_12'],'PREVENT'),
('poros_puntos_negros','La nariz me brilla siempre aunque me ponga polvos encima.',4,ARRAY['poros','brillo','nariz','zona_12'],'PREVENT'),
('poros_puntos_negros','Tengo la piel grasa en la zona T y seca en las mejillas, no sé qué ponerme.',4,ARRAY['poros','zona T','mixta','zona_12'],'PREVENT'),
('poros_puntos_negros','Los poros de la nariz se me ven tanto que parecen cráteres.',5,ARRAY['poros','cráteres','visibles','zona_12'],'PREVENT'),
('poros_puntos_negros','Me obsesiono con exprimir los puntos negros y sé que no debería.',4,ARRAY['poros','exprimir','obsesión','zona_12'],'PREVENT'),
('poros_puntos_negros','He probado strips de poros, máscaras de carbón... y a los dos días vuelven.',5,ARRAY['poros','strips','frustración','zona_12'],'PREVENT'),
('poros_puntos_negros','La textura de mi nariz es horrible, parece piel de naranja.',4,ARRAY['poros','textura','nariz','zona_12'],'PREVENT'),
('poros_puntos_negros','Cuando me maquillo, la base se acumula en los poros y se ve peor.',4,ARRAY['poros','maquillaje','base','zona_12'],'PREVENT'),
('poros_puntos_negros','Tengo la nariz brillante a las dos horas de maquillarme.',4,ARRAY['poros','brillo','maquillaje','zona_12'],'PREVENT'),
('poros_puntos_negros','Los poros de la nariz han ido creciendo con los años y ya no se cierran.',4,ARRAY['poros','creciendo','años','zona_12'],'PREVENT'),
('poros_puntos_negros','Con el calor, los poros de la nariz se me abren y se ven muchísimo.',3,ARRAY['poros','calor','verano','zona_12'],'PREVENT'),
('poros_puntos_negros','He usado mil productos para los puntos negros y ninguno funciona de verdad.',5,ARRAY['poros','productos','frustración','zona_12'],'PREVENT'),
('poros_puntos_negros','La zona de la nariz y el mentón siempre está grasienta aunque me limpie bien.',4,ARRAY['poros','grasa','limpieza','zona_12'],'PREVENT'),
('poros_puntos_negros','Los poros de la nariz me generan complejo y no sé cómo solucionarlo.',5,ARRAY['poros','complejo','solución','zona_12'],'PREVENT'),

-- ZONA 13 — Frente Zona T
('brillo_zona_t','Tengo las rayas de la frente marcadísimas y cada vez se ven más.',4,ARRAY['zona T','frente','arrugas','zona_13'],'PREVENT'),
('brillo_zona_t','Me han salido tres líneas horizontales en la frente y no puedo quitármelas de la cabeza.',4,ARRAY['zona T','líneas','frente','zona_13'],'PREVENT'),
('brillo_zona_t','Cuando no me maquillo se me ven unas arrugas en la frente que me hacen parecer mayor.',4,ARRAY['zona T','maquillaje','arrugas','zona_13'],'PREVENT'),
('brillo_zona_t','Frunzo el ceño sin darme cuenta y ya tengo esas líneas grabadas.',4,ARRAY['zona T','ceño','líneas','zona_13'],'PREVENT'),
('brillo_zona_t','Mi frente parece un papel arrugado cuando levanto las cejas.',3,ARRAY['zona T','frente','textura','zona_13'],'PREVENT'),
('brillo_zona_t','Me he dado cuenta de que tengo la frente con textura, no está lisa como antes.',3,ARRAY['zona T','textura','lisa','zona_13'],'PREVENT'),
('brillo_zona_t','Las líneas de la frente se me notan incluso con base de maquillaje.',4,ARRAY['zona T','maquillaje','base','zona_13'],'PREVENT'),
('brillo_zona_t','Me preocupa que a mi edad ya tenga estas arrugas tan marcadas en la frente.',4,ARRAY['zona T','edad','preocupación','zona_13'],'PREVENT'),
('brillo_zona_t','Parece que estoy siempre preocupada o concentrada aunque esté tranquila.',4,ARRAY['zona T','expresión','estrés','zona_13'],'PREVENT'),
('brillo_zona_t','Tengo la frente muy brillante y con poros grandes, no sé cómo equilibrarla.',4,ARRAY['zona T','brillo','poros','zona_13'],'PREVENT'),
('brillo_zona_t','Duermo bien pero me levanto con la frente tensa y con marcas.',3,ARRAY['zona T','tensión','mañana','zona_13'],'PREVENT'),
('brillo_zona_t','He empezado a notar que las arrugas de la frente no desaparecen aunque relaje la cara.',4,ARRAY['zona T','estáticas','relajar','zona_13'],'PREVENT'),
('brillo_zona_t','El estrés del trabajo se me ha instalado en la frente, literalmente.',5,ARRAY['zona T','estrés','trabajo','zona_13'],'PREVENT'),
('brillo_zona_t','Mi frente está apagada y sin vida, no tiene ese brillo que tenía antes.',3,ARRAY['zona T','apagada','luminosidad','zona_13'],'PREVENT'),
('brillo_zona_t','Me han dicho que debería ponerme bótox en la frente y no quiero llegar a eso.',5,ARRAY['zona T','bótox','alternativa','zona_13'],'PREVENT'),

-- ZONA 14 — Contorno Mandíbula
('contorno_perdido','He perdido la definición de la mandíbula y ya no tengo contorno.',5,ARRAY['contorno','mandíbula','definición','zona_14'],'RECLAIM'),
('contorno_perdido','Me ha salido una papada y no sé de dónde ha venido.',5,ARRAY['contorno','papada','repentina','zona_14'],'RECLAIM'),
('contorno_perdido','El óvalo de mi cara se ha desdibujado y la mandíbula ya no se marca.',5,ARRAY['contorno','óvalo','mandíbula','zona_14'],'RECLAIM'),
('contorno_perdido','Tengo como unas bolsitas a los lados de la barbilla que antes no tenía.',4,ARRAY['contorno','jowl','barbilla','zona_14'],'RECLAIM'),
('contorno_perdido','Mi cara ya no termina en la mandíbula, se confunde con el cuello.',5,ARRAY['contorno','cuello','mandíbula','zona_14'],'RECLAIM'),
('contorno_perdido','He adelgazado y la piel me ha quedado colgando en la mandíbula.',4,ARRAY['contorno','adelgazar','colgante','zona_14'],'RECLAIM'),
('contorno_perdido','Me preocupa esa zona entre la mandíbula y el cuello que se ha ablandado.',4,ARRAY['contorno','ablandado','cuello','zona_14'],'RECLAIM'),
('contorno_perdido','Noto que la mandíbula ya no se me ve en las fotos de perfil.',4,ARRAY['contorno','fotos','perfil','zona_14'],'RECLAIM'),
('contorno_perdido','He perdido el ángulo de la mandíbula que tan bien me quedaba antes.',4,ARRAY['contorno','ángulo','mandíbula','zona_14'],'RECLAIM'),
('contorno_perdido','Tengo la sensación de que toda la cara me ha bajado hacia la mandíbula.',4,ARRAY['contorno','bajado','cara','zona_14'],'RECLAIM'),
('contorno_perdido','La papada lateral me hace la cara más cuadrada y más pesada.',4,ARRAY['contorno','papada lateral','peso','zona_14'],'RECLAIM'),
('contorno_perdido','Por las mañanas el contorno de la mandíbula se ve muy hinchado y sin definición.',3,ARRAY['contorno','hinchado','mañana','zona_14'],'RECLAIM'),
('contorno_perdido','Antes mi mandíbula era firme y ahora se ve blanda y sin tono.',5,ARRAY['contorno','firmeza','tono','zona_14'],'RECLAIM'),
('contorno_perdido','He visto fotos mías de hace unos años y el contorno era completamente diferente.',4,ARRAY['contorno','fotos','comparación','zona_14'],'RECLAIM'),
('contorno_perdido','La zona de la barbilla y la mandíbula ha perdido firmeza y se ve caída.',4,ARRAY['contorno','barbilla','caída','zona_14'],'RECLAIM'),

-- ZONA 15 — Sienes
('sienes_hundidas','Se me han hundido las sienes y me hace la cara muy esquelética.',5,ARRAY['sienes','hundidas','esquelética','zona_15'],'RECLAIM'),
('sienes_hundidas','Tengo las sienes hundidas y la cara parece más pequeña que antes.',5,ARRAY['sienes','pequeña','hundidas','zona_15'],'RECLAIM'),
('sienes_hundidas','He perdido volumen en la zona de las sienes y me cambia toda la cara.',4,ARRAY['sienes','volumen','cara','zona_15'],'RECLAIM'),
('sienes_hundidas','Las sienes hundidas me hacen parecer mucho mayor de lo que soy.',5,ARRAY['sienes','mayor','hundidas','zona_15'],'RECLAIM'),
('sienes_hundidas','He adelgazado y las sienes se me han quedado vacías.',4,ARRAY['sienes','adelgazar','vacías','zona_15'],'RECLAIM'),
('sienes_hundidas','La zona lateral de la frente se me ha hundido y crea una sombra fea.',4,ARRAY['sienes','lateral','sombra','zona_15'],'RECLAIM'),
('sienes_hundidas','Noto que las cejas me han bajado en las puntas y me mira mal.',3,ARRAY['sienes','cejas','bajado','zona_15'],'RECLAIM'),
('sienes_hundidas','Las arrugas de la pata de gallo se me han profundizado mucho.',4,ARRAY['sienes','pata de gallo','arrugas','zona_15'],'RECLAIM'),
('sienes_hundidas','Tengo la zona de la sien apagada y sin vida comparada con el resto.',3,ARRAY['sienes','apagada','contraste','zona_15'],'RECLAIM'),
('sienes_hundidas','Me han dicho que me ponga filler en las sienes para recuperar el volumen.',5,ARRAY['sienes','filler','volumen','zona_15'],'RECLAIM'),
('sienes_hundidas','La sien derecha se me ha hundido más que la izquierda y se nota la asimetría.',3,ARRAY['sienes','asimetría','derecha','zona_15'],'RECLAIM'),
('sienes_hundidas','Desde que tengo bruxismo noto que las sienes se me han vaciado más.',4,ARRAY['sienes','bruxismo','vaciado','zona_15'],'RECLAIM'),
('sienes_hundidas','La zona temporal me da aspecto de estar enferma o muy cansada.',4,ARRAY['sienes','enferma','cansancio','zona_15'],'RECLAIM'),
('sienes_hundidas','He visto fotos antiguas y las sienes eran completamente distintas, más llenas.',4,ARRAY['sienes','fotos','comparación','zona_15'],'RECLAIM'),
('sienes_hundidas','Cuando me recojo el pelo se me notan mucho las sienes hundidas.',5,ARRAY['sienes','pelo recogido','hundidas','zona_15'],'RECLAIM');


-- VERIFICACIÓN — ejecuta esto después del INSERT
