INSERT INTO skin_insights
  (line, age_group, technical_concept, yadala_translation,
   desire_level_1, desire_level_2, sensoriality, priority, tags)
VALUES

('RECOVER', '30-45',
 'Hiperactividad del músculo depresor de la comisura labial + pérdida de colágeno peribucal + ptosis de grasa subcutánea',
 'Las comisuras caen cuando los músculos que las sostienen pierden el equilibrio. Yadala reactiva los elevadores y estimula el colágeno de soporte para que la expresión vuelva a ser tuya.',
 'Recuperar control sobre mi expresión',
 'Volver a reconocerme cuando me miro al espejo',
 'No es que tu boca esté cayendo… es que tu piel y tus músculos han dejado de sostenerla.',
 4,
 ARRAY['comisuras','boca caída','cara triste','cara de enfadada','depresor','RECOVER','zona_01','tono_muscular']),

('PREVENT', '20-30',
 'Contracción crónica del músculo frontal + degradación de colágeno dérmico por estrés oxidativo + luz azul',
 'Las rayas de la frente no son edad — son tensión acumulada. Yadala alivia la fascia frontal, activa el colágeno y protege frente al daño de las pantallas.',
 'Prevenir sin dramatizar',
 'Piel que exprese calma, no estrés',
 'Esas líneas de la frente no son arrugas. Son el mapa de todo lo que has procesado sin descansar tu piel.',
 3,
 ARRAY['frente','arrugas frente','líneas horizontales','rayas frente','frontal','pantallas','PREVENT','zona_02','estres_oxidativo']),

('RECOVER', '30-45',
 'Enlentecimiento de microcirculación periorbitaria + estasis linfático + dermis ultrafina infraorbitaria con déficit de colágeno',
 'Las ojeras no son suciedad ni cansancio — son circulación lenta. Yadala activa el flujo capilar y el drenaje linfático para que la zona bajo el ojo vuelva a tener luz.',
 'Verse descansada aunque no haya dormido más',
 'Recuperar la mirada viva',
 'Tus ojeras no mienten. Son la prueba de que esa piel lleva años sin recibir oxígeno suficiente.',
 5,
 ARRAY['ojeras','bolsas','ojos hinchados','cansancio','periorbitaria','drenaje','RECOVER','zona_03','microcirculacion']),

('RECLAIM', '45+',
 'Ptosis de grasa malar + relajación del SMAS + pérdida de tono cigomático + reducción de colágeno tipo I y III en dermis malar',
 'Los pómulos no desaparecen — lo que se pierde es el músculo que los eleva, el colágeno que los sostiene y la grasa que los rellena. Yadala trabaja en las tres capas.',
 'Volver a reconocerme · Recuperar mi estructura',
 'Sentir que mi cara vuelve a ser la mía',
 'Tu cara no ha cambiado de forma. Lo que ha cambiado es el soporte que la sostenía. Y eso sí se puede activar.',
 4,
 ARRAY['pomulos','mejillas caídas','cara plana','volumén facial','cigomático','SMAS','RECLAIM','zona_04','menopausia']),

('RECOVER', '30-45',
 'Profundización del pliegue nasogeniano por ptosis de grasa malar + déficit de colágeno tipo III + debilitamiento de músculo elevador + relajación del SMAS mediofacial',
 'El surco no aparece porque envejezcas — aparece porque la piel que lo rodea ha dejado de sostenerse. Yadala estimula el colágeno, activa los elevadores y trabaja el SMAS para suavizarlo desde dentro.',
 'Recuperar el contorno del tercio medio',
 'Entender qué está pasando y tener una solución real',
 'No es que te hayas hecho mayor. Es que esa zona lleva años sin recibir la señal de que tiene que sostenerse. Yadala se la devuelve.',
 5,
 ARRAY['surco nasogeniano','pliegues sonrisa','líneas sonrisa','cara de bulldog','nasogeniano','RECOVER','zona_05','colágeno','glicina']),

('PREVENT', '20-30',
 'Hipercontracción crónica del corrugador y procerus + formación de arrugas glabelares estáticas + tensión miofascial por estrés digital',
 'Las líneas del entrecejo no son de edad — son de estrés instalado. Yadala libera la tensión miofascial, activa el colágeno y suaviza el signo del 11 sin paralizar tu expresión.',
 'Expresión serena · Soltar la tensión visible',
 'Dejar de parecer enfadada cuando estoy tranquila',
 'Esas rayas entre tus cejas no son arrugas de edad. Son años de concentración, preocupación y pantallas grabados en tu piel.',
 3,
 ARRAY['entrecejo','signo del 11','ceño fruncido','rayas entrecejo','corrugador','procerus','PREVENT','zona_06','tensión_miofascial']),

('RECLAIM', '45+',
 'Relajación del platisma + descenso del SMAS + pérdida de colágeno cervical + text neck + formación de bandas platismales',
 'El cuello envejece más rápido que la cara porque nadie lo cuida. Yadala activa el platisma, tonifica el SMAS y estimula el colágeno cervical para devolver definición al óvalo.',
 'Recuperar el contorno · Verse entera, no fragmentada',
 'Que el cuello no traicione lo que la cara muestra',
 'El cuello es la zona que más envejece y la que menos cuidas. Yadala trabaja donde nadie llega.',
 4,
 ARRAY['cuello','papada','óvalo caído','platisma','SMAS','mandíbula','text neck','RECLAIM','zona_07','bandas cervicales']),

('RECLAIM', '45+',
 'Adelgazamiento del orbicular de los labios + código de barras peribucal + pérdida de definición del bermellón + déficit de colágeno tipo I peribucal',
 'Los labios se afinan porque el músculo que los da volumen pierde tono y el colágeno que los sostiene disminuye. Yadala reactiva ambos para devolver definición y presencia a la boca.',
 'Recuperar la expresión · Verse entera y presente',
 'Que mi boca vuelva a tener presencia sin rellenos',
 'Tu boca lleva toda la vida expresándolo todo. Ya es hora de que alguien la cuide a ella.',
 3,
 ARRAY['labios','código de barras','contorno labial','labios finos','orbicular','peribucal','RECLAIM','zona_08','bermellón']),

('RECOVER', '30-45',
 'Hipertrofia del masetero por bruxismo + tensión miofascial crónica + ensanchamiento del tercio inferior + pérdida de definición mandibular',
 'La mandíbula tensa no es solo una cuestión estética — es estrés acumulado en el músculo más fuerte de tu cara. Yadala alivia la tensión miofascial y oxigena un tejido cronicamente contraído.',
 'Soltar la tensión · Descansar el rostro',
 'Recuperar el contorno sin bótox en el masetero',
 'Tu mandíbula carga con todo el estrés que no has soltado. Yadala le da permiso para descansar.',
 3,
 ARRAY['mandíbula','masetero','bruxismo','cara cuadrada','tensión mandibular','RECOVER','zona_09','tensión_miofascial','estrés']),

('RECOVER', '30-45',
 'Ptosis palpebral funcional + adelgazamiento de la piel del párpado superior + pérdida del pliegue palpebral + debilitamiento del elevador del párpado',
 'El párpado no cae por edad — cae porque la piel ultrafina de esa zona ha perdido colágeno y el músculo elevador ha perdido tono. Yadala activa ambos para recuperar la apertura de la mirada.',
 'Recuperar la mirada · Verse presente y viva',
 'Que mis ojos vuelvan a expresar lo que siento',
 'Tu párpado no ha caído porque eres mayor. Ha caído porque nadie le ha dado la señal de que tiene que sostenerse.',
 3,
 ARRAY['párpado caído','mirada pequeña','ojos cansados','ptosis','elevador párpado','blefaroplastia','RECOVER','zona_10','piel fina palpebral']),

('RECLAIM', '45+',
 'Atrofia de grasa malar profunda + relajación del SMAS malar + pérdida de proyección cigomática + impacto de menopausia en distribución de grasa facial',
 'El pómulo no desaparece — pierde el soporte que lo mantenía proyectado. Yadala estimula el colágeno y la tensión fascial del área malar para recuperar estructura y presencia sin rellenos.',
 'Recuperar la estructura · Verse con carácter y presencia',
 'Que mi cara vuelva a tener su forma sin filler',
 'Tu pómulo no ha desaparecido. Solo está esperando que alguien le recuerde que tiene que sostenerse.',
 4,
 ARRAY['pómulo','área malar','pómulos hundidos','volumen facial','menopausia','SMAS malar','RECLAIM','zona_11','grasa malar']),

('PREVENT', '20-30',
 'Dilatación folicular por desequilibrio sebáceo + oxidación del sebo (comedones abiertos) + alteración del pH del manto ácido + microbiota desregulada',
 'Los puntos negros no son suciedad — son sebo oxidado. Los poros no se cierran — se regulan. Yadala equilibra el pH y el manto ácido para que dejen de abrirse.',
 'Piel limpia y uniforme · Sin filtros · Sin maquillaje',
 'Controlar los poros sin agredir la piel',
 'Los puntos negros no son suciedad. Son sebo oxidado. Y los poros no se cierran — se afinan.',
 4,
 ARRAY['poros','puntos negros','piel grasa','nariz brillante','zona T','comedones','PREVENT','zona_12','pH','microbiota']),

('PREVENT', '20-30',
 'Hipersecreción sebácea en zona T frontal + desequilibrio del manto ácido + poros dilatados en frente + combinación grasa-seca',
 'El brillo de la frente no es culpa tuya — es tu piel compensando un desequilibrio de pH. Yadala regula la secreción sebácea desde dentro para una piel más mate y uniforme sin resecarla.',
 'Prevenir sin dramatizar · Piel equilibrada y sin brillo excesivo',
 'Que la frente no brille a las dos horas de maquillarme',
 'La frente brillante no es suciedad. Es tu piel produciendo más sebo del necesario porque el pH está desregulado.',
 3,
 ARRAY['frente grasa','zona T','brillo','poros frente','sebo','manto ácido','PREVENT','zona_13','piel mixta']),

('RECLAIM', '45+',
 'Relajación de ligamentos faciales mandibulares + descenso del SMAS inferior + formación de jowls + pérdida de ángulo mandibular',
 'El óvalo no se pierde de golpe — se pierde milímetro a milímetro mientras los ligamentos que lo sostienen se relajan. Yadala activa la tensión fascial para recuperar la definición del contorno sin cirugía.',
 'Recuperar el contorno · Verse definida y presente',
 'Que la mandíbula vuelva a ser visible en las fotos',
 'El óvalo no se pierde de golpe. Se pierde milímetro a milímetro mientras nadie activa los ligamentos que lo sostienen.',
 4,
 ARRAY['contorno','papada lateral','jowl','mandíbula difusa','ligamentos faciales','SMAS inferior','RECLAIM','zona_14','óvalo caído']),

('RECLAIM', '45+',
 'Atrofia del músculo temporal + pérdida de grasa temporal profunda y superficial + hundimiento de la zona temporal + asimetría lateral',
 'Las sienes hundidas son el cambio más invisible del envejecimiento y el más impactante. Yadala activa el músculo temporal y mejora la microcirculación de una zona cronicamente olvidada.',
 'Recuperar el volumen lateral · Verse entera y presente',
 'Que la cara vuelva a tener su forma completa',
 'Tu cara no ha encogido. Solo ha perdido el músculo que la llenaba de vida. Yadala se lo devuelve.',
 3,
 ARRAY['sienes','sienes hundidas','zona temporal','cara pequeña','músculo temporal','RECLAIM','zona_15','volumen temporal','asimetría']);

-- VERIFICACIÓN
-- SELECT COUNT(*) FROM skin_insights; -- debe dar 15
-- SELECT line, COUNT(*) FROM skin_insights GROUP BY line;
